-- MySQL Script generated by MySQL Workbench
-- Sb 17 apr 2021 19:12:26 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Newlife
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Newlife
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Newlife` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Newlife` ;

-- -----------------------------------------------------
-- Table `Newlife`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Newlife`.`users` (
  `id_user` INT NOT NULL,
  `name_user` VARCHAR(45) NOT NULL,
  `surname_user` VARCHAR(45) NOT NULL,
  `date_of_birth_user` DATE NOT NULL,
  `place_of_birth_user` VARCHAR(45) NOT NULL,
  `e_mail_user` VARCHAR(45) NOT NULL,
  `username_user` VARCHAR(45) NOT NULL,
  `description_user` VARCHAR(100) NOT NULL,
  `photo_users` BLOB NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Newlife`.`feelings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Newlife`.`feelings` (
  `id_feeling` INT NOT NULL AUTO_INCREMENT,
  `title_post` VARCHAR(145) NOT NULL,
  `content_post` VARCHAR(300) NOT NULL,
  `date_post` DATE NOT NULL,
  PRIMARY KEY (`id_feeling`),
  CONSTRAINT `fk_post_1`
    FOREIGN KEY (`id_feeling`)
    REFERENCES `Newlife`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Newlife`.`friendship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Newlife`.`friendship` (
  `sender_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  PRIMARY KEY (`sender_id`, `recipient_id`),
  INDEX `fk_friendship_users2_idx` (`recipient_id` ASC) VISIBLE,
  CONSTRAINT `fk_friendship_users1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `Newlife`.`users` (`id_user`),
  CONSTRAINT `fk_friendship_users2`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `Newlife`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Newlife`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Newlife`.`status` (
  `pending` VARCHAR(45) NOT NULL,
  `accepted` VARCHAR(45) NOT NULL,
  `declined` VARCHAR(45) NOT NULL,
  `blocked` VARCHAR(45) NULL DEFAULT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Newlife`.`friendship_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Newlife`.`friendship_status` (
  `sender_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  `id_status` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`sender_id`, `recipient_id`),
  INDEX `fk_friendship_status_status1_idx` (`recipient_id` ASC) VISIBLE,
  CONSTRAINT `fk_friendship_status_friendship1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `Newlife`.`friendship` (`recipient_id`),
  CONSTRAINT `fk_friendship_status_status1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `Newlife`.`status` (`id_status`),
  CONSTRAINT `fk_friendship_status_users1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `Newlife`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Newlife`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Newlife`.`posts` (
  `id_post` INT NOT NULL,
  `title_post` VARCHAR(45) NULL DEFAULT NULL,
  `content_post` VARCHAR(300) NOT NULL,
  `date_post` DATE NOT NULL,
  `photo` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_post`),
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`id_post`)
    REFERENCES `Newlife`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
